// <auto-generated />
using System;
using JellyDev.WH40K.Infrastructure.Database.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JellyDev.WH40K.Infrastructure.Migrations
{
    [DbContext(typeof(FactionDbContext))]
    partial class FactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JellyDev.WH40K.Domain.Faction.FactionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Factions", "WH");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16fb2151-3ded-4e74-9215-cde3a68cf661"),
                            Created = new DateTime(2021, 10, 11, 3, 54, 15, 906, DateTimeKind.Utc).AddTicks(9116),
                            Name = "Necrons"
                        },
                        new
                        {
                            Id = new Guid("749a7624-9d4a-4426-b2aa-d00073379e51"),
                            Created = new DateTime(2021, 10, 11, 3, 54, 15, 906, DateTimeKind.Utc).AddTicks(9508),
                            Name = "Space Marines"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
